### ISSUE TITLE
Do you have some Readme files? of maybe FAQ? or maube somethink to quick start?

### ISSUE THREAD

**Issue by therb1** [frozie/oncall-schedule-planner#1]
Do you have some Readme files? of maybe FAQ? or maube somethink to quick start?

**Comment by frozie** [comment]
I wrote up a quick start readme. If some things are unclear you can ask or find the answer and fix the readme. Note this project is not yet ready for production and needs more work. If you want to start contributing then I might merge a few enhancements developed internally in my company to this repo.

**Comment by therb1** [comment]
Thank you for your quick response. Your decision does not suit us. We use the linkedin oncall as web ui and write our software plannig python. Your ideas are very cool anyway
